disallowed-methods = [
    # Do not use the `std::fs` method below, use their `fs_err` equivalent
    # The `std::fs` methods fail with 'No such file or directory' if the path does not exist, but do not print the problematic path
    # See: https://docs.rs/fs-err/latest/fs_err/
    "std::fs::canonicalize",
    "std::fs::copy",
    "std::fs::create_dir",
    "std::fs::create_dir_all",
    "std::fs::hard_link",
    "std::fs::metadata",
    "std::fs::read",
    "std::fs::read_dir",
    "std::fs::read_link",
    "std::fs::read_to_string",
    "std::fs::remove_dir",
    "std::fs::remove_dir_all",
    "std::fs::remove_file",
    "std::fs::rename",
    "std::fs::set_permissions",
    "std::fs::soft_link",
    "std::fs::symlink_metadata",
    "std::fs::write",
    "std::path::Path::canonicalize", # Use fs_err::canonicalize instead
]